name: build
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew check
      - name: Verify JReleaser configuration
        env:
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
        run: ./gradlew jreleaserConfig --stacktrace
      - name: Upload reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports-build
          path: '**/build/reports'

  publish:
    name: "publish"
    needs:
      - build
    if: ${{ github.ref == 'refs/heads/main' || startswith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'gradle'
      - name: Build artifacts
        env:
          SIGNING_PRIVATE_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          SIGNING_PASSWORD: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
        run: ./gradlew publish
      - name: Deploy artifacts
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
        run: ./gradlew jreleaserDeploy